### ISSUE TITLE
New Controller - Philips Hue dimmer switch  929002398602

### ISSUE THREAD

**Issue by gerritjonker** [EPMatt/awesome-ha-blueprints#137]
### Manufacturer

Philips/Signify

### Model

RWL022

### Short Description

New dimmer switch with Hue logo on off button

### Image

![929002398602](https://user-images.githubusercontent.com/20167906/131901317-e9bfbf72-e6da-4107-9b3e-5beec4813a57.jpg)

### [Zigbee2MQTT]

Same actions as older models

### Additional Details

- [ ] I'd like to help developing this blueprint.

### Useful resources

https://www.zigbee2mqtt.io/devices/929002398602.html#philips-929002398602

Pressing on button:
`MQTT publish: topic 'zigbee2mqtt/HueDimmer1', payload '{"action":"on_press","battery":100,"linkquality":72}'
Info MQTT publish: topic 'zigbee2mqtt/HueDimmer1', payload '{"action":"","battery":100,"linkquality":72}'
Info MQTT publish: topic 'zigbee2mqtt/HueDimmer1/action', payload 'on_press'
Info MQTT publish: topic 'zigbee2mqtt/HueDimmer1', payload '{"action":"on_press_release","battery":100,"linkquality":72}'
Info MQTT publish: topic 'zigbee2mqtt/HueDimmer1', payload '{"action":"","battery":100,"linkquality":72}'
Info MQTT publish: topic 'zigbee2mqtt/HueDimmer1/action', payload 'on_press_release'`

Text in helper: `{"trigger_action": "on_press", "last_triggered": "2021-09-01 22:21:11.461335+02:00"}`

Other action names: 

- "on_hold"
- "up_press"
- "up_hold"
- "down_press"
- "down_hold"
- "off_press"
- "off_hold"

### Additional context

Looks like the dashes are replaced bij underscores.
Automation is triggered but conditions are not met.
`Result:
result: false
conditions/0

Executed: 2 september 2021 21:13:00
Result:
result: false
entities: []`

Always willing to provide more information but sometimes I need some help with that ;)

**Comment by gottgenk** [comment]
These are all the zigbee2MQTT payloads I can find for this new V2 hue dimmer switch:
The payloads seem to be the same, the intended functions by Philips seem to be different however. Hope this helps.

`on_press`: On action -> New on/off button on the top of the remote, should be used to turn on, but also to turn of the lights now
`on_press_release`: On releasing the button
`on_hold`: On button holding longer
`on_hold_release`: Releasing after holding the on button longer
`off_press`: Hue action, this is the new HUE button on the bottom, it still sends payload for OFF like the older version. Hue-function should be changing scenes or color/whiteness with this button according to Philips.
`off_press_release`: Releasing the Hue button
`off_hold`: Holding the HUE button
`off_hold_release`: Releasing the HUE button after long hold
`up_press`: Pressing the up intensity button (large light logo)
`up_press_release`: Releasing the up intensity button
`up_hold`: Holding up intensity button
`up_hold_release`: Releasing after long hold
`down_press`: Press the lower intensity button (small light logo)
`down_press_release`: Releasing the button
`down_hold`: Holding the lower intensity button
`down_hold_release`: Releasing after longer hold

**Comment by EPMatt** [comment]
Hi @gerritjonker @gottgenk,

thank you so much for your suggestion! I'm happy to add support for this controller to our project. :) 
I'll let you know as soon as a blueprint for this device and hooks support are ready to be tested. Changes will be included in a Pull Request which will be linked to this issue. We could then continue our conversation for proper testing and feedback there.

Thanks!
