### ISSUE TITLE
New Controller - IKEA Styrbar

### ISSUE THREAD

**Issue by andersr8n** [EPMatt/awesome-ha-blueprints#148]
### Manufacturer

IKEA

### Model

E2001/E2002

### Short Description

TRÅDFRI STYRBAR remote control

### Image

![E2001-E2002](https://user-images.githubusercontent.com/74185377/135731504-1747e124-e9aa-4efc-85ea-2b4c8afc020c.jpg)
![styrbar-fjaerrkontroll-vit__0956695_pe804773_s5](https://user-images.githubusercontent.com/74185377/135731763-373808ec-25a9-4497-a93f-4ee4d2adf482.png)

### [Integration] (e.g. deCONZ, ZHA, Zigbee2MQTT)

- `action_name (e.g. button_press)`: action description (e.g. sent when pressing the button)
- etc.

### Additional Details

- [ ] I'd like to help developing this blueprint.

### Useful resources

Zigbee2MQTT doc
https://www.zigbee2mqtt.io/devices/E2001_E2002.html#ikea-e2001%252Fe2002

**Comment by EPMatt** [comment]
Hi @andersr8n  @bboti86,

Thank you so much for opening a feature request. I've just opened a PR (#171) which includes the controller blueprint for the IKEA E2001/E2002, as well as adding support for the Light and Media Player hooks.

We can continue the discussion regarding this feature in the linked PR.

Thanks! :)
