### ISSUE TITLE
[Security] Workflow ci_pr.yml is using vulnerable action reviewdog/action-eslint

### ISSUE THREAD

**Issue by fockboi-lgtm** [EPMatt/awesome-ha-blueprints#217]
The workflow ci_pr.yml is referencing action reviewdog/action-eslint using references v1. However this reference is missing the commit [7b45345d875d4979afe88b630dbc01a40e8a2e91](https://github.com/reviewdog/action-eslint/commits/7b45345d875d4979afe88b630dbc01a40e8a2e91) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by EPMatt** [comment]
Hi @fockboi-lgtm,

thank you for reporting the vulnerability.
Even if the `v1` tag should track the latest `v1` minor version, I'll force the action to the latest version in the workflow config file. 

Thanks again. :)
