### ISSUE TITLE
Bug - MediaHook IKEA Remote N2

### ISSUE THREAD

**Issue by r100gs** [EPMatt/awesome-ha-blueprints#222]
### Blueprint name

Media Hook

### Home Assistant Core Version

2021.12.4

### Home Assistant Installation Type

Home Assistant Supervised

### Description

IKEA Remote N2 via deconz/phoscon cannot be choosen as controller

### Automation YAML config

```yaml
media hook blueprint
```

### To Reproduce

1. Go to media hook blueprint
2. Click on new auatomation
3. Try to choose Ikea Remote N2

### Expected behavior

Remote N2 can be choosen

### Actual Behaviour

nothing to choose, only shortcut button

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

**Comment by EPMatt** [comment]
Hi @r100gs,

thank you for reporting here and for your patience, I'm sorry for my late response. 

From your report I guess you're unable to select the remote as a valid value for the `controller_device` input, from the HA UI.
The `controller_device` input does not impose any strict check on the provided value; you should indeed be able to select any device currently registered in your HA instance, (even non-controller devices).

Please check that your device is properly integrated in Home Assistant by navigating to the _Devices_ section in the HA configuration tab, and looking for the remote in the list of available devices. If the device does not appear in the list it might have been disabled, or some issues might have been encountered during the pairing process with deCONZ. If that's the case, I'd suggest you to reset the remote, repeat the pairing and try again.

Please let me know if you're able to solve the issue or if you need additional guidance.
Thanks! :)
