### ISSUE TITLE
[BUG] lights hook - color temperature not available from color mode selection

### ISSUE THREAD

**Issue by ewestein** [EPMatt/awesome-ha-blueprints#24]
**Bug Details**

- Blueprint name: Hook - Light
- Home Assistant Core Version: 2021.3.4
- Home Assistant Installation Type: Home Assistant OS

**Description**
Home Assistant Visual Editor for Automation based on Hook - Lights does not list the option 'Color Temperature' in the '(Optional) Light color mode' pull down. Looking at the light.yaml line 51-54 the option is not included. 

**To Reproduce**

1. Go to 'Edit Automation'
2. Click on 'Pull down menu 'Light color mode'
3. Option 'Color Temperature' is not available for selection

**Expected behavior**
Option 'Color Temperature' can be selected

**Actual Behaviour**
Option 'Color Temperature' is not available

**Additional context**
Editing my light.yaml file and adding the option 'Color Temperature' under the light_color_mode selector works with E1810 remote and IKEA Leptiter lights (deCONZ).

**Comment by EPMatt** [comment]
Hi @ewestein, thank you for reporting here.

I see the `RGB` option is present, but it's indeed not used in the blueprint's code.
I'm pushing a fix for this issue right now. :)

**Comment by EPMatt** [comment]
Hi @ewestein,

I've just pushed a fix, you can now update the blueprint.
Please let me know if this solves your issue. :)
Thank you!

**Comment by ewestein** [comment]
Hi @EPMatt,

I just updated the blueprint and can confirm the fix is working and the issue is solved. 

Thanks for your quick reply and fix! Much appreciated.

**Comment by EPMatt** [comment]
Hi @ewestein, thank you for your feedback.
I'm closing this issue. Glad to hear that your problem is solved. :) 

Happy automating! 🚀
