### ISSUE TITLE
Use time record attribute for last_triggered storage

### ISSUE THREAD

**Issue by calisro** [EPMatt/awesome-ha-blueprints#240]
### Blueprint name

Simple Safe Scheduler

### Description

Would it be possible to use attributes instead of state for the last_triggered and other storage?  This would remove the need to create multiple helpers for a single blueprint automation.  We could then simply use the time helper for both time and storage.

### Additional Details

- [ ] I'd like to help developing this feature/improvement.

**Comment by EPMatt** [comment]
Hi @calisro,

thank you for your suggestion and for your patience. I'm sorry for my late response.

That's a really interesting idea, I agree that it would make easier to set up automations with this blueprint.
Back when I first developed this blueprint it was not possible to retrieve the last time the automation run successfully, so I had to implement it via adding the `helper_storage` text input, using it as a storage area for the automation.

Do you have any idea on how we could implement such feature without relying on the additional `helper_storage` input? I read that support for accessing the automation object within the automation itself was recently added in Home Assistant Core, but I haven't had the time to look at it in detail yet.

Thanks! :)
