### ISSUE TITLE
New Controller - Philips Hue Wall Switch Module

### ISSUE THREAD

**Issue by Pferdebockwurst** [EPMatt/awesome-ha-blueprints#246]
### Manufacturer

Philips Hue

### Model

9290030171

### Short Description

Hue Wall Switch Module

### Image

https://www.assets.signify.com/is/image/Signify/b145375b19f34f7abc39ac4e00a53375?wid=1500&hei=1125&qlt=82

### Zigbee2MQTT

- 4 device modes: single_rocker, dual_rocker, single_push_button, dual_push_button
- left_press (short press of button one, not released)
- left_press_release (when released after a short press of button one)
- left_hold (continuously when longer press of button one, after left_press) [only when device mode is button]
- left_hold_release (when released after a longer press of button one) [only when device mode is button]

Those four actions exist for the right button too, but only when configured as dual_rocker or dual_push_button.

### Additional Details

- [X] I'd like to help developing this blueprint.

### Useful resources

https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/philips.js [lines 1858 to 1874]

**Comment by EPMatt** [comment]
Hi @Pferdebockwurst,

thank you so much for your suggestion! I'm happy to add support for this controller to our project. :) 
I'll let you know as soon as a blueprint for this device and hooks support are ready to be tested. Changes will be included in a Pull Request which will be linked to this issue. We could then continue our conversation for proper testing and feedback there.

Thanks!

**Comment by Pferdebockwurst** [comment]
Hey @EPMatt, awesome! Thank you let me know if I can help by testing or giving every information you might need!

**Comment by tamueller** [comment]
Haha, whow - I just found this project, and it looks promising. Since this is one of my most used controllers in my setup, I'd be happy to see this implemented. I can also help by providing example events or testing.

**Comment by EPMatt** [comment]
Hi @tamueller,

thank you for jumping into the discussion! We currently have the Zigbee2MQTT events for this controller, but I wasn't able to find any info regarding other integrations (ZHA, deCONZ, HUE) on the Internet.

Which integration are you using to connect your remotes to Home Assistant? If using something different from Z2M, could you please provide the events corresponding to the different interactions with the remote?

Thank you so much for your help!

**Comment by Leissson** [comment]
> Hi @tamueller,
> 
> thank you for jumping into the discussion! We currently have the Zigbee2MQTT events for this controller, but I wasn't able to find any info regarding other integrations (ZHA, deCONZ, HUE) on the Internet.
> 
> Which integration are you using to connect your remotes to Home Assistant? If using something different from Z2M, could you please provide the events corresponding to the different interactions with the remote?
> 
> Thank you so much for your help!

@EPMatt 

These are hue_events, subtype 2 for button 2

Event 100 fired 11:26:
{
    "event_type": "hue_event",
    "data": {
        "id": "hue_wall_switch_module_1_button",
        "device_id": "d35f276a7f91ffe75e42679a832629d3",
        "unique_id": "d5fa29e6-bf3b-4860-a000-3cd87f7f1d07",
        "type": "long_release",
        "subtype": 1
    },
    "origin": "LOCAL",
    "time_fired": "2022-02-17T09:26:04.908226+00:00",
    "context": {
        "id": "0ef69b22c70ac3e3ead2caa7bebe856e",
        "parent_id": null,
        "user_id": null
    }
}
Event 99 fired 11:26:
{
    "event_type": "hue_event",
    "data": {
        "id": "hue_wall_switch_module_1_button",
        "device_id": "d35f276a7f91ffe75e42679a832629d3",
        "unique_id": "d5fa29e6-bf3b-4860-a000-3cd87f7f1d07",
        "type": "repeat",
        "subtype": 1
    },
    "origin": "LOCAL",
    "time_fired": "2022-02-17T09:26:03.904797+00:00",
    "context": {
        "id": "4ae7985f8e584a2baef1a8f40618253a",
        "parent_id": null,
        "user_id": null
    }
}
Event 98 fired 11:26:
{
    "event_type": "hue_event",
    "data": {
        "id": "hue_wall_switch_module_1_button",
        "device_id": "d35f276a7f91ffe75e42679a832629d3",
        "unique_id": "d5fa29e6-bf3b-4860-a000-3cd87f7f1d07",
        "type": "repeat",
        "subtype": 1
    },
    "origin": "LOCAL",
    "time_fired": "2022-02-17T09:26:02.880507+00:00",
    "context": {
        "id": "acb035f0960cc1b76ccc884545fa0345",
        "parent_id": null,
        "user_id": null
    }
}
Event 97 fired 11:26:
{
    "event_type": "hue_event",
    "data": {
        "id": "hue_wall_switch_module_1_button",
        "device_id": "d35f276a7f91ffe75e42679a832629d3",
        "unique_id": "d5fa29e6-bf3b-4860-a000-3cd87f7f1d07",
        "type": "initial_press",
        "subtype": 1
    },
    "origin": "LOCAL",
    "time_fired": "2022-02-17T09:26:01.874461+00:00",
    "context": {
        "id": "ca457f74c922f0b9d6f4fea894780e15",
        "parent_id": null,
        "user_id": null
    }
}
Event 96 fired 11:26:
{
    "event_type": "hue_event",
    "data": {
        "id": "hue_wall_switch_module_1_button",
        "device_id": "d35f276a7f91ffe75e42679a832629d3",
        "unique_id": "d5fa29e6-bf3b-4860-a000-3cd87f7f1d07",
        "type": "short_release",
        "subtype": 1
    },
    "origin": "LOCAL",
    "time_fired": "2022-02-17T09:26:00.337112+00:00",
    "context": {
        "id": "72956db059ccc7dd2c2bb6c87475af53",
        "parent_id": null,
        "user_id": null
    }
}

**Comment by Pferdebockwurst** [comment]
Great to see some progress here! Is there any way I can participate, maybe some testing?

**Comment by zamolxe** [comment]
Here you have the info on deCONZ events:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4566#issuecomment-812474154

Example output on a short push/release:
Event 1 fired 3:35 PM:

{
    "event_type": "deconz_event",
    "data": {
        "id": "zbwsw03_kitchen_ceiling",
        "unique_id": "00:17:88:XX:XX:XX:XX:XX",
        "event": 1002,
        "device_id": "ed1644dd68e357ec2b83fc54c42bf0bc"
    },
    "origin": "LOCAL",
    "time_fired": "2022-02-17T14:35:59.275950+00:00",
    "context": {
        "id": "0f4481502e2667c000fe8a8740ea096b",
        "parent_id": null,
        "user_id": null
    }
}

Event 0 fired 3:35 PM:

{
    "event_type": "deconz_event",
    "data": {
        "id": "zbwsw03_kitchen_ceiling",
        "unique_id": "00:17:88:XX:XX:XX:XX:XX",
        "event": 1000,
        "device_id": "ed1644dd68e357ec2b83fc54c42bf0bc"
    },
    "origin": "LOCAL",
    "time_fired": "2022-02-17T14:35:59.075639+00:00",
    "context": {
        "id": "93799b2e21b779d82a85c6c00ea8a561",
        "parent_id": null,
        "user_id": null
    }
}

**Comment by Leissson** [comment]
To my knowledge, I don't think module has ZHA support yet. So it's either deconz, z2m or hue.

**Comment by tamueller** [comment]
And similar to the hue dimmer switches for the deconz_event event: 1000 is initial press, 1001 is hold, 1002 is short press release and 1003 is long press release. For button 2 the event is it is 200x.

Those events are if you set up the switch as a rocker, if I remember correctly for the other setting you only get 1001 and 1002, events, but they look identical.

Let me know if you need full examples of 1001 and 1003 events too, or if this is enough in combination with what @zamolex posted.

**Comment by Pferdebockwurst** [comment]
Hey @EPMatt,

is there any way I can help to bring this further? I would really like to see some progress here, but I don't know where to start.

Best regards,
Chris

**Comment by Pferdebockwurst** [comment]
Maybe the owner of this repository is busy with other things. Unfortunately I can't code this on my own, but I'm willing to test and debug if someone else can give it a try. Please message me if you're interested.

**Comment by chpego** [comment]
With **ZHA Integration** there is some event:

````yaml
event_type: zha_event
data:
  device_ieee: 00:17:******************
  unique_id: 00:17:******************
  device_id: 3cbe4fd001***************
  endpoint_id: 1
  cluster_id: 64512
  command: left_press_release
  args:
    button: left
    press_type: press_release
    command_id: 0
    args:
      - 1
      - 3145728
      - 2
      - 33
      - 1
      - 0
  params: {}
origin: LOCAL
time_fired: "2023-02-20T18:26:38.907769+00:00"
context:
  id: 01GSR17TNV0RR0TMQC8V45XT8Z
  parent_id: null
  user_id: null
````

````yaml
event_type: zha_event
data:
  device_ieee: 00:17:******************
  unique_id: 00:17:******************
  device_id: 3cbe4fd001***************
  endpoint_id: 1
  cluster_id: 64512
  command: left_press
  args:
    button: left
    press_type: press
    command_id: 0
    args:
      - 1
      - 3145728
      - 0
      - 33
      - 0
      - 0
  params: {}
origin: LOCAL
time_fired: "2023-02-20T18:26:38.808459+00:00"
context:
  id: 01GSR17TJRWSBH0NH25M57RAHF
  parent_id: null
  user_id: null

**Comment by Pferdebockwurst** [comment]
This seems dead.
