### ISSUE TITLE
New Controller - Aqara Wireless Mini Switch

### ISSUE THREAD

**Issue by lmgarret** [EPMatt/awesome-ha-blueprints#299]
### Manufacturer

Xiaomi

### Model

WXKG11LM

### Short Description

Aqara Wireless Mini Switch

### Image

![xiaomi-aqara-xiaomi-aqara-wireless-mini-switch(1)](https://user-images.githubusercontent.com/9049104/160807437-80df0059-bb2b-4b86-80d4-3d1580c2a6f7.png)

### ZHA

- `remote_button_short_press`: sent when clicking the button
- `remote_button_double_press`: sent when double clicking the button
- `remote_button_long_press`: sent when continuously pressing the button
- `remote_button_long_release`: sent when releasing the button after a long press

### Additional Details

- [X] I'd like to help developing this blueprint.

### Additional context

The device is pretty simple but it would still be nice to support it I guess! I don't have z2mqtt installed but I can report what's posted in which mqtt topic if needed.
Thanks for this great tool btw!

**Comment by EPMatt** [comment]
Hi @lmgarret,

thank you so much for your suggestion! I'm happy to add support for this controller to our project. :) 
I'll let you know as soon as a blueprint for this device and hooks support are ready to be tested. Changes will be included in a Pull Request which will be linked to this issue. We could then continue our conversation for proper testing and feedback there.

Thanks!

**Comment by EPMatt** [comment]
@lmgarret  I see you provided events for ZHA. Could you also please look for action mappings for this controller regarding Zigbee2MQTT and deCONZ? It would be awesome if we could support the device with those integrations as well. :)

Thank you so much for your precious help!

**Comment by lmgarret** [comment]
Sorry I'm a bit late to respond; I just redid my setup with zigbee2mqtt, and I saw that @azrael-kun submitted a PR for this, thanks! How can I help test this PR on Z2M?

**Comment by Azrael-Kun** [comment]
@lmgarret In my PR the bot has posted URLs for the blueprints (https://github.com/EPMatt/awesome-ha-blueprints/pull/328#issuecomment-1122953863). You should be able to import these into Home Assistant and then create an automation using them. I grabbed the Z2M events from their device page so I would appreciate someone confirming they are correct as I haven't gotten around to creating my test instance yet.

**Comment by lmgarret** [comment]
Thanks ! I tested your blueprint in my setup and can confirm the Z2M codes are correct :tada:

**Comment by EPMatt** [comment]
⚠️ Important announcement about the project: #371 ⚠️ 

I'd like to kindly ask for your feedback about our work here. If you have time, please answer the poll in the above discussion. This will help shaping the future of Awesome HA Blueprints. 🚀 

Thank you!

**Comment by EPMatt** [comment]
Thank you for your suggestion and for your feedback @lmgarret @Azrael-Kun! I've just merged the PR and made changes available to the public. :)
