### ISSUE TITLE
New Controller - Sonoff SNZB-01 Button

### ISSUE THREAD

**Issue by catatonicChimp** [EPMatt/awesome-ha-blueprints#321]
### Manufacturer

Sonoff

### Model

SNZB-01

### Short Description

SNZB Wireless Switch

### Image

![image](https://user-images.githubusercontent.com/1394392/165275902-006fac33-dc12-4f95-81d9-5b4edb3cf913.png)

### [Zigbee2MQTT]

- `single`: sent after single press
- `double`: sent after double press
- `long`: sent after holding button for approx 3 seconds

### Additional Details

- [X] I'd like to help developing this blueprint.

**Comment by EPMatt** [comment]
⚠️ Important announcement about the project: #371 ⚠️ 

I'd like to kindly ask for your feedback about our work here. If you have time, please answer the poll in the above discussion. This will help shaping the future of Awesome HA Blueprints. 🚀 

Thank you!

**Comment by EPMatt** [comment]
Hi @catatonicChimp,

I'm terribly sorry for my long delay. Thank you so much for opening an issue here and providing Zigbee2MQTT actions for this controller.
@Azrael-Kun kindly put his time and efforts into developing a blueprint for the device, which I've just reviewed and made available to the public. The Zigbee2MQTT actions you provided here were included in the final blueprint.

You can find the new blueprint here: https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/sonoff_snzb01
If you have any questions or you experience any problems with it, feel free to open a new issue. I'd be happy to help. :)

Thank you for your patience and happy automating! 🔥
