### ISSUE TITLE
JsonDecoderException if double press helper is not a valid json

### ISSUE THREAD

**Issue by eloo** [EPMatt/awesome-ha-blueprints#45]
Thank you for taking the time to report here! :tada:

**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to process your request more rapidly.

This template should only be used to report a bug with a blueprint. If this is not your case, you can [choose a different issue template](https://github.com/EPMatt/awesome-ha-blueprints/issues/new/choose). If you have a question instead, please open a discussion [here](https://github.com/EPMatt/awesome-ha-blueprints/discussions/new).

\*_=required_

## Bug Details\*

- Blueprint name: Maybe all
- Home Assistant Core Version: no relevant
- Home Assistant Installation Type not relevant
- 
## Description\*

If a double press helper is configured and this helper has a non-json value the automation (controller) is not working because a jsondecoder expection is working.

I would suggest to catch such a case and maybe simple ignore this error and handle it the same as the helper is empty or throw a proper error which makes clear the helper is in an incompatible state and should be checked or cleared. 

## Automation YAML config\*

```yaml
The YAML code for the automation you're having problems with. This will allow to reproduce your issue.
```

## To Reproduce\*

Steps to reproduce the issue:

1. Create helper for double press
2. Fill helper with random string
3. Trigger the automation with has double press enabled (i use the shortcut blueprint)
4. See error in traces

## Expected behavior\*

* Ignore the invalid content and replace it with a new one
* Expose a proper error which indicates the real error (helper is in invalid state)

## Actual Behaviour\*

Automation is not working.

## Additional Details\*

- [ ] I'd like to help developing a fix for this issue.

## Additional context

Thanks
eloo

**Comment by EPMatt** [comment]
Hi @eloo,

thank you for reporting here. Are you experiencing this issue with the E1812 blueprint in `main` or the one proposed in #32? 
If you're using the blueprint from the PR linked above (I'm pretty sure you are referring to it) I think we should solve this issue before making the feature publicly available.

Thanks!

**Comment by eloo** [comment]
@EPMatt 
i have tested this with the code from #32 yes and with the E1812 blueprint.
And yes sounds like a good idea to fix this first ;)

**Comment by EPMatt** [comment]
Hi @eloo,

Ok, I'll take a look at it before merging the PR. :)
Thank you for reporting.
