### ISSUE TITLE
Controller blueprint for OSRAM Smart+ Switch Mini

### ISSUE THREAD

**Issue by EPMatt** [EPMatt/awesome-ha-blueprints#65]
Thank you for taking the time to report here! :tada:

**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to process your request more rapidly.

This template should only be used to propose a new blueprint. If this is not your case, you can [choose a different issue template](https://github.com/EPMatt/awesome-ha-blueprints/issues/new/choose). If you have a question instead, please open a discussion [here](https://github.com/EPMatt/awesome-ha-blueprints/discussions/new).

\*_=required_

## Description\*

Controller blueprint for the [OSRAM Smart+ Switch Mini](https://www.amazon.it/gp/product/B074PZKX4G/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1) (AC025XX00NJ).

The controller comes in different colors, with different model names: AC0251100NJ / AC0251400NJ / AC0251600NJ / AC0251700NJ.

Suggestion received on the [HA Community Forum](https://community.home-assistant.io/t/zha-deconz-zigbee2mqtt-ikea-e1743-on-off-switch-dimmer-universal-blueprint-all-actions-double-click-events-control-lights-media-players-and-more-with-hooks/277861/42).

## Additional Details\*

- [X] I'd like to help developing this blueprint
- [X] I've found a blueprint/automation not included in this project which achieves the same/similar goal
  - [Z2M blueprint for the OSRAM Smart+ Switch Mini](https://community.home-assistant.io/t/zigbee2mqtt-osram-smart-switch-mini-ac0251100nj-ac0251700nj-actions/263589)

**Comment by alexdelprete** [comment]
Next time I'll open a feature request here. Thanks.

**Comment by EPMatt** [comment]
Hi @alexdelprete,

I was able to find the action mappings for both ZHA and deCONZ, as stated in [ControllerX documentation](https://xaviml.github.io/controllerx/). I'm now working on the blueprint. I'll open a Pull Request as soon as it's ready, so we can test it before making it publicly available. :) 

Thank you!

**Comment by alexdelprete** [comment]
Didn't know about ControllerX, it's a nice idea, something that should be implemented into HA directly. I prefer not to install appdaemon so I will not use it unfortunately.

So here's the page you needed: https://xaviml.github.io/controllerx/controllers/OSRAM-AC025XX00NJ

I see that actions for Zigbe2MQTT are not mentioned, but you can take those from the other [blueprint ](https://community.home-assistant.io/t/zigbee2mqtt-osram-smart-switch-mini-ac0251100nj-ac0251700nj-actions/263589)I I linked in the forum, right? 

Matteo, thank you so much. :)

**Comment by EPMatt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add support for OSRAM Smart+ Switch Mini](https://trello.com/c/np0PObXN/49-add-support-for-osram-smart-switch-mini)

**Comment by alexdelprete** [comment]
Can't access that Trello card, it says it might be private. :)

My account on trello is @alexdelprete.

**Comment by EPMatt** [comment]
Hi @alexdelprete,

> Didn't know about ControllerX, it's a nice idea, something that should be implemented into HA directly. I prefer not to install appdaemon so I will not use it unfortunately.

Thank you for the resource. Actually ControllerX is a really useful and interesting app, which has tons of supported controllers and features. I was one of its first users and I've always been satisfied in using it.

In fact, this collection of blueprints takes inspiration from the core idea of ControllerX: integrating controllers in Home Assistant with ease. But what we're trying to do here is removing the AppDaemon dependency by integrating controllers directly into Home Assistant with just a couple of automations, as well as extending controllers functionality by adding virtual events which are not natively supported by them, such as double presses. The result is better performance, simpler setup, less dependencies and more features. :) 


> I see that actions for Zigbe2MQTT are not mentioned, but you can take those from the other blueprint I I linked in the forum, right?

Sure. :)

**Comment by EPMatt** [comment]
> Can't access that Trello card, it says it might be private. :)
> 
> My account on trello is @alexdelprete.

Don't worry, I was only experimenting with Trello and GitHub a bit. Ended up throwing away the whole project board. :)

**Comment by alexdelprete** [comment]
> But what we're trying to do here is removing the AppDaemon dependency by integrating controllers directly into Home Assistant with just a couple of automations, as well as extending controllers functionality by adding virtual events which are not natively supported by them, such as double presses. The result is better performance, simpler setup, less dependencies and more features.

Exactly what I hope to achieve. :)

Talk to you soon.

**Comment by alexdelprete** [comment]
> Don't worry, I was only experimenting with Trello and GitHub a bit. Ended up throwing away the whole project board. :)

No problem. I'll wait for your instructions to test the BP.
