### ISSUE TITLE
helper_last_controller_event description

### ISSUE THREAD

**Issue by alexdelprete** [EPMatt/awesome-ha-blueprints#76]
## Report Details\*

- Documentation URL: link to the documentation page you are opening this report for, if applicable
- Blueprint name: if this issue is related to a blueprint's documentation, provide the name of the related blueprint

## Description\*

The `helper_last_controller_event` should be described in the general page of the Controller automation, not in a specific controller page.

## Suggested changes\*

A clear and concise description of which changes you'd suggest.

## Additional Details\*

- [ ] I'd like to help improving the documentation by working on this issue.

**Comment by EPMatt** [comment]
Hi @alexdelprete, 
thank you for opening this issue.
I'll update the documentation by adding a dedicated paragraph in the [Controllers-Hooks general documentation page](https://epmatt.github.io/awesome-ha-blueprints/docs/controllers-hooks-ecosystem). :)

**Comment by alexdelprete** [comment]
Good idea. :)

**Comment by EPMatt** [comment]
@alexdelprete I've just updated the docs website. I've also added a generic section for virtual double press events. See the linked PR for all the implemented changes.

What do you think about it? Is the new documentation clear in your opinion? :)

**Comment by alexdelprete** [comment]
Yes, it's clear enough, at least for me. :)

Thank you.

**Comment by EPMatt** [comment]
Great, thank you for your feedback. :)
