### ISSUE TITLE
New Controller - Aqara Opple switch

### ISSUE THREAD

**Issue by antonholmstedt** [EPMatt/awesome-ha-blueprints#88]
Thank you for taking the time to report here! :tada:

**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to process your request more rapidly.

This template should only be used to propose support for a a new Controller blueprint. If this is not your case, you can [choose a different issue template](https://github.com/EPMatt/awesome-ha-blueprints/issues/new/choose). If you have a question instead, please open a discussion [here](https://github.com/EPMatt/awesome-ha-blueprints/discussions/new).

\*_=required_

## Controller Information\*

- Manufacturer: Xiaomi
- Model: 
WXCJKG12LM
- Short Description: Aqara Opple 2/4/6 button remote.
- Image:

## Actions

button_1_single
button_2_single
button_3_single
button_4_single
button_5_single
button_6_single

button_1_double
button_2_double
button_3_double
button_4_double
button_5_double
button_6_double

button_1_triple
button_2_triple
button_3_triple
button_4_triple
button_5_triple
button_6_triple

button_1_hold
button_2_hold
button_3_hold
button_4_hold
button_5_hold
button_6_hold

button_1_release
button_2_release
button_3_release
button_4_release
button_5_release
button_6_release

### [Integration] (e.g. deCONZ, ZHA, Zigbee2MQTT)

Zigbee2MQTT, not sure of how the other two works.

- `action_name (e.g. button_press)`: action description (e.g. sent when pressing the button)
- etc.

## Additional Details\*

- [ ] I'd like to help developing this blueprint
- [ ] I've found a blueprint/automation not included in this project which integrates this controller
  - Link to the resources you've found: [Zigbee2mqtt - Aqara Opple switch 3 bands](https://community.home-assistant.io/t/zigbee2mqtt-aqara-opple-switch-3-bands/256212)

## Additional context

Add any other context about the controller here (pitfalls in the device, checks which should be implemented to provide a fully working integration for the device, etc.).

**Comment by EPMatt** [comment]
Hi @antonholmstedt, thank you for your suggestion.

I'll look around for deCONZ and ZHA action mappings for this device, then I'll move to implement the controller blueprint. I'll let you know as soon as it's ready. :) 

Thanks again!
